version: "3.8"
services:
  taskpro.frontend:
    build: ./taskpro-front
    ports:
      - 3000:3000
    depends_on:
      - taskpro.backend
    environment:
      - NEXT_PUBLIC_API_URL=https://localhost:8080
  taskpro.backend:
    build: ./TaskPro-back
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT_KEY=aBcDeFgHiJkLmNoPqRsTuVwXyZ123456789acedfdasdfsdsad
      - SQLServerConnectionString=Server=host.docker.internal,1433;Database=TaskPro; User Id=SA; Password=P@SSWORD12345; TrustServerCertificate=True
      - MongoConnectionString=mongodb://host.docker.internal:27017
      - Database=TaskPro
      - CommentCollectionName=Comments
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - taskpro.mongo
      - taskpro.sqlserver
  taskpro.mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  taskpro.sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@SSWORD12345"
      ACCEPT_EULA: "Y"
    volumes:
      - sql-data:/var/opt/mssql
    ports:
      - 1433:1433

volumes:
  mongo-data:
  sql-data:
